name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lighthouse Check
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://oceanbennett.com/
            https://oceanbennett.com/404.html
          uploadArtifacts: false
          temporaryPublicStorage: true
